server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: autoblog_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: autoblog_logs
          __path__: /var/log/autoblog/*.log

  - job_name: autoblog_data
    static_configs:
      - targets:
          - localhost
        labels:
          job: autoblog_data
          __path__: /var/data/autoblog/*/*.json
    pipeline_stages:
      - json:
          expressions:
            job_id: job_id
            timestamp: timestamp
            status: status
      - labels:
          job_id:
          status: 